import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, Check } from "lucide-react";
import { arbor } from "@/api/arbor";
import { useSession } from "@/auth/session";
import { Button, EmptyBlock, ErrorBlock, LoadingBlock, PageHeader, Panel } from "@/components/app-ui";
import { formatDate, notificationText } from "@/lib/display";

export default function Notifications() {
  const { token } = useSession();
  const client = useQueryClient();
  const rows = useQuery({ queryKey: ["notifications"], queryFn: () => arbor.notifications(token!) });
  const read = useMutation({
    mutationFn: (id: string) => arbor.markNotificationRead(token!, id),
    onSuccess: () => void client.invalidateQueries({ queryKey: ["notifications"] }),
  });
  if (rows.isLoading) return <LoadingBlock label="Loading notifications…"/>;
  if (rows.isError) return <ErrorBlock message="Notifications could not be loaded." retry={() => void rows.refetch()}/>;
  return <div><PageHeader eyebrow="Activity" title="Notifications" description="Notifications are generated by backend workflows such as repository metadata processing."/>{rows.data?.length ? <Panel><div className="notification-list">{rows.data.map(item => <article className={item.read ? "notification-row" : "notification-row unread"} key={item.id}><BellRing size={18}/><div><strong>{item.kind.replaceAll(/[._-]/g, " ")}</strong><p>{notificationText(item.body)}</p><time>{formatDate(item.created_at)}</time></div>{!item.read && <Button variant="quiet" aria-label="Mark as read" onClick={() => read.mutate(item.id)} disabled={read.isPending && read.variables === item.id}><Check size={17}/></Button>}</article>)}</div></Panel> : <Panel><EmptyBlock title="No notifications" description="New activity will appear here when the backend generates it."/></Panel>}</div>;
}
